# Develop override settings

url: http://localhost:4000

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-HTWCHJRC6J"

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded